// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.6.3
// - protoc             v3.21.5
// source: v1/echo.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationEchoServiceSay = "/v1.EchoService/Say"

type EchoServiceHTTPServer interface {
	Say(context.Context, *SayRequest) (*SayResponse, error)
}

func RegisterEchoServiceHTTPServer(s *http.Server, srv EchoServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/echo/say", _EchoService_Say0_HTTP_Handler(srv))
}

func _EchoService_Say0_HTTP_Handler(srv EchoServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SayRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEchoServiceSay)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Say(ctx, req.(*SayRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SayResponse)
		return ctx.Result(200, reply)
	}
}

type EchoServiceHTTPClient interface {
	Say(ctx context.Context, req *SayRequest, opts ...http.CallOption) (rsp *SayResponse, err error)
}

type EchoServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewEchoServiceHTTPClient(client *http.Client) EchoServiceHTTPClient {
	return &EchoServiceHTTPClientImpl{client}
}

func (c *EchoServiceHTTPClientImpl) Say(ctx context.Context, in *SayRequest, opts ...http.CallOption) (*SayResponse, error) {
	var out SayResponse
	pattern := "/api/echo/say"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEchoServiceSay))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
